version: '3.8'
services:
  discord_bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - grafana
    volumes:
      - '/var/lib/emoji-counter/sqlite-data:/var/lib/discord-bot'
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
    - GF_INSTALL_PLUGINS=frser-sqlite-datasource
    user: '0'
    ports:
      - 3000:3000
    volumes:
      - '/var/lib/emoji-counter/data:/var/lib/grafana'
      - '/var/lib/emoji-counter/sqlite-data:/var/lib/discord-bot'
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - /var/lib/emoji-counter/matomo:/var/www/html:z,rw
      - /var/lib/emoji-counter/nginx.conf:/etc/nginx/conf.d/default.conf:z,rw
      - /var/lib/emoji-counter/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
